"""Changed requestor_id to receiver_id

Revision ID: 399bffab5e9f
Revises: 3a2ee18d786a
Create Date: 2026-07-13 06:28:20.452751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399bffab5e9f'
down_revision: Union[str, Sequence[str], None] = '3a2ee18d786a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('friendships_requester_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('friendships', 'requester_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_requester_id_fkey'), 'friendships', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.drop_column('friendships', 'receiver_id')
    # ### end Alembic commands ###
