"""Remove is_liked field from Likes table

Revision ID: 6ae73b3b5931
Revises: 9876d9d5950d
Create Date: 2026-07-17 07:07:07.474319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae73b3b5931'
down_revision: Union[str, Sequence[str], None] = '9876d9d5950d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_liked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
